// Forma común para licitaciones, OC y compra agil
export function crearEntidadMp({
    source = 'mercado-publico',
    module,
    externalCode = '',
    title = '',
    description = '',
    statusCode = '',
    statusLabel = '',
    buyerName = '',
    buyerRut = '',
    buyerRegion = '',
    amount = 0,
    currency = 'CLP',
    publishedAt = null,
    closingAt = null,
    items = [],
    raw = null,
  } = {}) {
    return {
      source,
      module,
      externalCode: String(externalCode ?? ''),
      title: title || 'Sin título',
      description: description || '',
      statusCode: statusCode != null ? String(statusCode) : '',
      statusLabel: statusLabel || 'Sin estado',
      buyerName: buyerName || 'Sin organismo',
      buyerRut: buyerRut || '',
      buyerRegion: buyerRegion != null ? String(buyerRegion) : '',
      amount: Number(amount) || 0,
      currency: currency || 'CLP',
      publishedAt,
      closingAt,
      items: Array.isArray(items) ? items : [],
      raw,
    };
  }